name: cargo clippy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  clippy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.51
          profile: minimal
          override: true
      - run: rustup component add clippy
      - run: cargo clippy --all-features -- -D warnings
